---
# - name: Create EC2 instances
#   amazon.aws.ec2_instance:
#     name: "{{ item.name }}"
#     key_name: "{{key_name}}"
#     instance_type: "{{type}}"
#     security_group: "{{security_group}}"
#     region: "{{region}}"
#     aws_access_key: "{{ec2_access_key}}"  # From vault as defined
#     aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
#     network:
#       assign_public_ip: true
#     image_id: "{{ item.image }}"
#     tags:
#       environment: "{{ item.name }}"
#     loop: 
#       - {image: "ami-04b70fa74e45c3917", name: "manage-node-1"}
#       - {image: "ami-0f58b397bc5c1f2e8", name: "manage-node-2"}
#       - {image: "ami-0f58b397bc5c1f2e8", name: "manage-node-3"}


# - name: start an instance with a public IP address
#   amazon.aws.ec2_instance:
#     name: "ansible-instance"
#     # key_name: "prod-ssh-key"
#     # vpc_subnet_id: subnet-013744e41e8088axx
#     instance_type: "{{type}}"
#     security_group: "{{security_group}}"
#     region: "{{region}}"
#     aws_access_key: "{{ec2_access_key}}"  # From vault as defined
#     aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined  
#     key_name: "{{key_name}}"    
#     network:
#       assign_public_ip: true
#     image_id: "{{image_id}}"
#     # tags:
#     #   Environment: Testing